### ISSUE TITLE
Extract Features Issue

### ISSUE THREAD

**Issue by ertza** [dmbb/MPTAnalysis#1]
Hi I'm having a hard time using `extractFeatures.py` . It raises the following error:

 `File "/usr/local/lib/python2.7/site-packages/dpkt/dpkt.py", line 92, in __init__          `
`raise NeedData`
  `    dpkt.dpkt.NeedData`

I think it is some issue with my datasets. 
I just placed pcaps into folders with the same name as the pcap file into 
> MPTAnalysis/DeltaShaperAnalysis/TrafficCaptures

e.g.

> MPTAnalysis/DeltaShaperAnalysis/TrafficCaptures/mytest.pcap/mytest.pcap

If you could please share what format the dataset needs to be in for it to work, I'll be highly grateful.

**Comment by dmbb** [comment]
Sorry for the delay. The dataset with the packet captures is already linked in the README for a while.
