### ISSUE TITLE
Traffic Captures

### ISSUE THREAD

**Issue by Kkevsterrr** [dmbb/MPTAnalysis#2]
Hi @dmbb - 

I was fascinated by your paper. I'm interested in exploring your methodology and learning more about your work, but I noticed the traffic captures were never added to this Github. Is there any way you could post them or make them available? I'm happy to reach out privately as well if needed. Thank you!

**Comment by dmbb** [comment]
Hello @Kkevsterrr ,

Thank you for your interest in our paper! I'm sorry for the delay, you may find our traffic captures at https://turbina.gsd.inesc-id.pt/resources/resources.html
